# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 宝宝树前端团队
email: fe@babytree-inc.com
description: > # this means to ignore newlines until "baseurl:"
    宝宝树前端项目组技术博客，欢迎补充
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
paginate: 1
paginate_path: "blog/page:num"

# Build settings
#markdown: kramdown 
# Conversion
#markdown: kramdown
highlighter: pygments
markdown: rdiscount
rdiscount:
   extensions:
     - footnotes
lsi: false
excerpt_separator: "\n\n\n\n"

markdown_ext: markdown,mkd,mkdn,md

github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-coffeescript
    - jekyll-paginate
